#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

LIGHTTPD_LOGFILE="${LIGHTTPD_LOGFILE:-/var/log/lighttpd/lighttpd.log}";
LIGHTTPD_USER="${LIGHTTPD_USER:-lighttpd}";

if [ -z "${APCUPSD_HEADLESS}" ];
then
    if [ -z "${LIGHTTPD_SKIP_LOGFIFO}" ]; # set to 'true' to disable
    then
        vecho "Starting lighttpd-logger";
        rm -f ${LIGHTTPD_LOGFILE}; # if exists
        mkfifo -m 600 ${LIGHTTPD_LOGFILE};
        chown ${LIGHTTPD_USER}:${LIGHTTPD_USER} ${LIGHTTPD_LOGFILE};
        cat <> ${LIGHTTPD_LOGFILE} # to stdout
        # cat <> ${LIGHTTPD_LOGFILE} 1>&2  # to stderr
    else # let lighttpd log to regular file instead
        vecho "Skip starting lighttpd-logger.";
        sleep infinity;
    fi;
else
    vecho "Skip starting lighttpd-logger.";
    sleep infinity;
fi;
