#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

if [ -n "${APCUPSD_HEADLESS}" ]; then exit 0; fi;
# else configure lighttpd
#
LIGHTTPD_CONFDIR="${LIGHTTPD_CONFDIR:-/etc/lighttpd}";
LIGHTTPD_LOGFILE="${LIGHTTPD_LOGFILE:-/var/log/lighttpd/lighttpd.log}";
LIGHTTPD_USER="${LIGHTTPD_USER:-lighttpd}";

vecho "Ensure configuration directory exists: ${LIGHTTPD_CONFDIR}";
mkdir -p \
    ${LIGHTTPD_CONFDIR} \
    $(dirname ${LIGHTTPD_LOGFILE}) \
    ;

# function to substitute paths in config files
_subst () {
    sed \
    -e "s|LIGHTTPD_USER|$LIGHTTPD_USER|g" \
    -e "s|LIGHTTPD_LOGFILE|$LIGHTTPD_LOGFILE|g" \
    $1 > $2;
}

# make sure lighttpd conf exists
if [ ! -f ${LIGHTTPD_CONFDIR}/lighttpd.conf ];
then
    vecho "Setting up default Lighttpd configurations at ${LIGHTTPD_CONFDIR}/lighttpd.conf.";
    _subst /defaults/lighttpd.conf ${LIGHTTPD_CONFDIR}/lighttpd.conf;
fi;

if [ ! -f ${LIGHTTPD_CONFDIR}/apcupsd.conf ];
then
    vecho "Setting up Lighttpd configurations for apcUPSd at ${LIGHTTPD_CONFDIR}/apcupsd.conf.";
    _subst /defaults/apcupsd.lighttpd.conf ${LIGHTTPD_CONFDIR}/apcupsd.conf;
fi;

