#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

LIGHTTPD_CONFDIR="${LIGHTTPD_CONFDIR:-/etc/lighttpd}";
LIGHTTPD_ARGS="${LIGHTTPD_ARGS:- -D}";

if [ -z "${APCUPSD_HEADLESS}" ];
then
    vecho "Starting lighttpd";
    exec \
        lighttpd \
        -f ${LIGHTTPD_CONFDIR}/lighttpd.conf \
        ${LIGHTTPD_ARGS} \
        ;
else
    vecho "Skip starting lighttpd.";
    sleep infinity;
fi;
